FROM alpine:latest as builder

ARG NGINX_VERSION=1.21.1
ARG NGINX_RTMP_VERSION=1.2.2
ARG FFMPEG_VERSION=4.4

RUN	apk update		&&	\
	apk add				\
		git			\
		gcc			\
		binutils		\
		gmp			\
		isl			\
		libgomp			\
		libatomic		\
		libgcc			\
		openssl			\
		pkgconf			\
		pkgconfig		\
		mpc1			\
		libstdc++		\
		ca-certificates		\
		libssh2			\
		expat			\
		pcre			\
		musl-dev		\
		libc-dev		\
		pcre-dev		\
		zlib-dev		\
		openssl-dev		\
		curl			\
		make


RUN	cd /tmp/									&&	\
	curl --remote-name http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz			&&	\
	git clone https://github.com/arut/nginx-rtmp-module.git -b v${NGINX_RTMP_VERSION}

RUN	cd /tmp										&&	\
	tar xzf nginx-${NGINX_VERSION}.tar.gz						&&	\
	rm nginx-${NGINX_VERSION}.tar.gz						&&      \
	cd nginx-${NGINX_VERSION}							&&	\
	./configure										\
		--prefix=/opt/nginx								\
		--with-http_ssl_module								\
		--add-module=../nginx-rtmp-module					&&	\
	make										&&	\
	make install

FROM alpine:latest as build-ffmpeg

ARG FFMPEG_VERSION
ARG PREFIX=/opt/
ARG MAKEFLAGS="-j4"

# FFmpeg build dependencies.
RUN apk add --update \
  build-base \
  coreutils \
  freetype-dev \
  lame-dev \
  libogg-dev \
  libass \
  libass-dev \
  libvpx-dev \
  libvorbis-dev \
  libwebp-dev \
  libtheora-dev \
  openssl-dev \
  opus-dev \
  pkgconf \
  pkgconfig \
  rtmpdump-dev \
  wget \
  x264-dev \
  x265-dev \
  yasm

RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
RUN apk add --update fdk-aac-dev

# Get FFmpeg source.
RUN cd /tmp/ && \
  wget http://ffmpeg.org/releases/ffmpeg-4.4.tar.gz && \
  tar zxf ffmpeg-4.4.tar.gz && rm ffmpeg-4.4.tar.gz

# Compile ffmpeg.
RUN cd /tmp/ffmpeg-4.4 && \
  ./configure \
  --prefix=${PREFIX} \
  --enable-version3 \
  --enable-gpl \
  --enable-nonfree \
  --enable-small \
  --enable-libmp3lame \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libvpx \
  --enable-libtheora \
  --enable-libvorbis \
  --enable-libopus \
  --enable-libfdk-aac \
  --enable-libass \
  --enable-libwebp \
  --enable-postproc \
  --enable-avresample \
  --enable-libfreetype \
  --enable-openssl \
  --disable-debug \
  --disable-doc \
  --disable-ffplay \
  --extra-libs="-lpthread -lm" && \
  make && make install && make distclean

# Cleanup.
#RUN rm -rf /var/cache/* /tmp/*


FROM alpine:latest
RUN     apk update              &&      \
        apk add                         \
		openssl			\
		libstdc++		\
		ca-certificates		\
		pcre			\
		gettext			\
		lame			\
		libogg			\
		curl			\
		libass			\
		libvpx			\
		libvorbis		\
		libwebp			\
		libtheora		\
		opus			\
		rtmpdump		\
		x264-dev		\
		x265-dev		\
                gcc                     


COPY --from=builder /opt/nginx /opt/nginx
#COPY --from=0 /tmp/nginx-rtmp-module/stat.xsl /opt/nginx/conf/stat.xsl
COPY --from=build-ffmpeg /opt/ /opt/
#COPY --from=build-ffmpeg /opt/lib/libfdk-aac.so.2 /opt/lib/libfdk-aac.so.2

RUN rm /opt/nginx/conf/nginx.conf

ADD run.sh /

EXPOSE 1935
EXPOSE 8080

CMD sh /run.sh
